services:
  - type: web
    name: aptino-claim-engine-api
    env: python
    buildCommand: pip install -r deployment/requirements.txt && python -m rag.indexer
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false

  - type: web
    name: aptino-claim-engine-ui
    env: python
    buildCommand: pip install -r deployment/requirements.txt
    startCommand: streamlit run frontend/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
